### ISSUE TITLE
Champion.gg wont update

### ISSUE THREAD

**Issue by hermondy** [MathiasWold/lolbuilds#3]
Last update on champion.gg was 10.20. Could you please check it?

![image](https://user-images.githubusercontent.com/22242037/99194875-202c0980-2761-11eb-9ab8-3a0a9386972a.png)

**Comment by i1u5** [comment]
Opgg is failing too.

**Comment by mathiaswold** [comment]
Hello!

@hermondy: The champion.gg version comes from [their website](https://champion.gg/) (see "Patch" in the header), and updates automatically as they update to a new patch. It looks like they used more time than usual to update their data from patch 10.20, but as of this time they are updated to 10.24, and I would think 10.25 is right around the corner.

@doomlerd: I'll have a look at it!

**Comment by mathiaswold** [comment]
Fixed in [v3.1.1](https://github.com/MathiasWold/lolbuilds/releases/latest)
