### ISSUE TITLE
Builds 1.3.1 crash

### ISSUE THREAD

**Issue by hermondy** [MathiasWold/lolbuilds#5]
Just downloaded version 1.3.1 and its not working. Everything single time the app closes right after i open it.

![image](https://user-images.githubusercontent.com/22242037/102283100-792dbf80-3f10-11eb-9242-c2867e2ea604.png)

**Comment by mathiaswold** [comment]
Hello,
Thanks for letting me know. It looks like champion.gg just updated their website's layout, which made the app crash. I've pushed [a new release (v3.1.2)](https://github.com/MathiasWold/lolbuilds/releases/latest) which disables championgg while I look into updating the app for the new site.
